[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback so /products, /admin etc. work after refresh
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
